server:
  port: 8090
vilin:
  address: http://www.${vilin.name}.com
  name: engineer_luo
  number: ${random.int}
  secret: ${random.value}

spring:
  profiles:
    active: dev
    
#freemarker配置
#  freemarker:
#    suffix: .html

  thymeleaf:
    prefix: classpath:/web/
    suffix: .html

 

#配置多环境
---
spring:
  profiles: test
server:
  port: 8091
vilin:
  name: engineer1_luo
logging:
  config: classpath:logback-core.xml
  
---
spring:
  profiles: dev
server:
  port: 8092
vilin:
  name: engineer2_luo