server:
  port: 8090
vilin:
  address: http://www.${vilin.name}.com
  name: engineer_luo
  number: ${random.int}
  secret: ${random.value}

spring:
  profiles:
    active: dev
    
#freemarker配置
#  freemarker:
#    suffix: .html

  thymeleaf:
    prefix: classpath:/web/
    suffix: .html

#datasource 
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=GMT%2B8
    username: root
    password: Lw@1985105
    driver-class-name: com.mysql.cj.jdbc.Driver
    
#JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true    

#Redis
  redis:
    host: localhost
    port: 6379
    
#ehcache
  cache:
    type: ehcache
    ehcache:
      config: classpath:config/ehcache.xml

#配置多环境
---
spring:
  profiles: test
server:
  port: 8091
vilin:
  name: engineer1_luo
logging:
  config: classpath:logback-core.xml
  
---
spring:
  profiles: dev
server:
  port: 8092
vilin:
  name: engineer2_luo